### ISSUE TITLE
Could not pass event PlayerViolationEvent to InfiniteJump v1.2.11

### ISSUE THREAD

**Issue by NESTOWL** [MrMicky-FR/InfiniteJump#10]
```
[10:54:33 ERROR]: Could not pass event PlayerViolationEvent to InfiniteJump v1.2.11
[10:54:33 ERROR]: Suspected Plugins:
[10:54:33 ERROR]:       Matrix{enabled,ver=6.0.2,path=plugins/Matrix_6.0.2_release.jar}
[10:54:33 ERROR]:       InfiniteJump{enabled,ver=1.2.11,path=plugins/InfiniteJump_v1.2.11.jar}
[10:54:33 ERROR]: Exception details below:
java.lang.NoSuchFieldError: SPEED
        at fr.mrmicky.infinitejump.anticheathooks.MatrixHook.onViolation(MatrixHook.java:25) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor148.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at me.rerere.matrix.llIllIIlIIIIIlI.lIlIlllllllIIIl(mh) ~[?:?]
        at me.rerere.matrix.lIlIIIIlllIlIll.IlllIlIIlIlIllI(ce) ~[?:?]
        at me.rerere.matrix.lllIlIlIllllIIl.IIllIlIllIlIllI(ph) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor99.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1326) ~[?:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1218) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1211) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1187) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1027) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
```

**Comment by MrMicky-FR** [comment]
This seems to be an issue with Matrix v6 but I can’t find the API for this version

**Comment by NESTOWL** [comment]
@MrMicky-FR Matrix plugin author replied
> use matrix jar as api

**Comment by NESTOWL** [comment]
@MrMicky-FR so what should I do?

**Comment by NESTOWL** [comment]
Thanks!
